AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Calendars:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-Calendars
  CalendarBlocks:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-CalendarBlocks
  BlockCalendars:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-BlockCalendars
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: BlockCalendars
      CodeUri: src
      Handler: main.block_calendars
      Runtime: python3.7
      MemorySize: !Ref EnvConfiglambdamemorysizeAsString
      Timeout: !Ref EnvConfiglambdatimeoutAsString
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarBlocks
        - DynamoDBCrudPolicy:
            TableName: !Ref Calendars
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt InterviewNotifications.TopicName
      Environment:
        Variables:
          TABLE_NAME: !Ref CalendarBlocks
          TABLE_ARN: !GetAtt CalendarBlocks.Arn
          TABLE_NAME_2: !Ref Calendars
          TABLE_ARN_2: !GetAtt Calendars.Arn
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          TOPIC_NAME: !GetAtt InterviewNotifications.TopicName
          TOPIC_ARN: !Ref InterviewNotifications
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 ? * 6 *)
          Metadata:
            StackeryName: BlockCalendarsTimer
  ClearBlocks:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-ClearBlocks
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: ClearBlocks
      CodeUri: src
      Handler: main.clear_blocks
      Runtime: python3.7
      MemorySize: !Ref EnvConfiglambdamemorysizeAsString
      Timeout: !Ref EnvConfiglambdatimeoutAsString
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarBlocks
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt InterviewNotifications.TopicName
      Events:
        Timer2:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 ? * 2 *)
          Metadata:
            StackeryName: ClearBlocksTimer
      Environment:
        Variables:
          TABLE_NAME: !Ref CalendarBlocks
          TABLE_ARN: !GetAtt CalendarBlocks.Arn
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          TOPIC_NAME: !GetAtt InterviewNotifications.TopicName
          TOPIC_ARN: !Ref InterviewNotifications
  InterviewNotifications:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-InterviewNotifications
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfiglambdamemorysizeAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/lambda/memory-size
  EnvConfiglambdatimeoutAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/lambda/timeout
Metadata:
  EnvConfigParameters:
    EnvConfiglambdamemorysizeAsString: lambda.memory-size
    EnvConfiglambdatimeoutAsString: lambda.timeout