#
#   Thiscovery API - THIS Institute’s citizen science platform
#   Copyright (C) 2019 THIS Institute
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   A copy of the GNU Affero General Public License is available in the
#   docs folder of this project.  It is also available www.gnu.org/licenses/
#
td = {
    'test_appointment_id': 399682887,
    'dev_appointment_id': 448161724,
    'dev_appointment_no_link_id': 451427483,
    'dev_appointment_no_link_participant_not_in_thiscovery_database_id': 450820094,
    'dev_appointment_no_link_participant_does_not_have_user_project': 451904182,
    'test_appointment_no_notif_id': 448161419,
    'past_test_appointment_id': 437321459,

    'test_appointment_type_id': 14792299,
    'dev_appointment_type_id': 14649911,
    'test_appointment_no_notif_type_id': 17268193,
    'dev_appointment_no_link_type_id': 17271544,

    'calendar_id': 4038206,
    'calendar_name': 'André',
    'email': 'clive@email.co.uk',
    'participant_user_id': '8518c7ed-1df4-45e9-8dc4-d49b57ae0663',
    'event_body': "action=appointment.scheduled&id=399682887&calendarID=4038206&appointmentTypeID=14792299",
    'past_appointment_event_body': "action=appointment.scheduled&id=437321459&calendarID=4038206&appointmentTypeID=14792299",
    'event_body_with_user_metadata': "action=appointment.scheduled&id=503637409&calendarID=4038206&appointmentTypeID=14792299",
    'cancelled_appointment_id': 446315771,
    'interview_url': "https://meet.myinterview.com/1b879c51-2e29-46ae-bd36-3199860e65f2",
    'project_task_id': '273b420e-09cb-419c-8b57-b393595dba78',
}

appointments = {
    'appointment1': {  # hasn't received initial notification yet
        "appointment_id": "399682887",
        "acuity_info": {
            "id": 399682887,
            "firstName": "Clive",
            "lastName": "Cresswell",
            "phone": "",
            "email": "clive@email.co.uk",
            "date": "June 30, 2020",
            "time": "10:15",
            "endTime": "10:45",
            "dateCreated": "June 29, 2020",
            "datetimeCreated": "2020-06-29T16:45:48-0500",
            "datetime": "2020-06-30T10:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Test appointment",
            "appointmentTypeID": 14792299,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "30",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=9d20ba8fc7801ff9bc599861c72937ca",
            "location": "",
            "notes": "DO NOT DELETE. Appointment used for automated testing.",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Clive Cresswell\nPhone: \nEmail: clive@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk"
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "clive@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-06-30",
        "appointment_type": {
            "type_id": "14792299",
            "name": "Test appointment",
            "category": "Tech development",
            "has_link": True,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "14792299",
            "type": "acuity-appointment-type"
        }
    },
    'appointment2': {  # last notification received 3 days before appointment
        "appointment_id": "448161724",
        "acuity_info": {
            "id": 448161724,
            "firstName": "Altha",
            "lastName": "Alcorn",
            "phone": "",
            "email": "altha@email.co.uk",
            "date": "September 28, 2020",
            "time": "13:00",
            "endTime": "13:30",
            "dateCreated": "September 25, 2020",
            "datetimeCreated": "2020-09-25T05:48:18-0500",
            "datetime": "2020-09-28T13:00:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment",
            "appointmentTypeID": 14649911,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "30",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=ab81fa72b0d0c1dead5057103c292bd3",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Altha Alcorn\nPhone: \nEmail: altha@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk"
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "altha@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "2020-09-25 06:10:10+00:00",
        "appointment_date": "2020-09-28",
        "appointment_type": {
            "type_id": "14649911",
            "name": "Development appointment",
            "category": "Tech development",
            "has_link": None,
            "send_notifications": None,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "14649911",
            "type": "acuity-appointment-type"
        }
    },
    'appointment3': {  # last notification received 1 day before appointment
        "appointment_id": "451427483",
        "acuity_info": {
            "id": 451427483,
            "firstName": "Clive",
            "lastName": "Cresswell",
            "phone": "",
            "email": "clive@email.co.uk",
            "date": "October 2, 2020",
            "time": "13:15",
            "endTime": "14:00",
            "dateCreated": "October 1, 2020",
            "datetimeCreated": "2020-10-01T05:11:03-0500",
            "datetime": "2020-10-02T13:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment - no link",
            "appointmentTypeID": 17271544,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "45",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=9edb5e9373f203a9398073e132eb0e7a",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Clive Cresswell\nPhone: \nEmail: clive@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk"
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "clive@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "2020-10-01 05:13:40+00:00",
        "appointment_date": "2020-10-02",
        "appointment_type": {
            "type_id": "17271544",
            "name": "Development appointment - no link",
            "category": "Tech development",
            "has_link": False,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17271544",
            "type": "acuity-appointment-type"
        }
    },
    'appointment4': {  # hasn't received initial notification yet
        "appointment_id": "450820094",
        "acuity_info": {
            "id": 450820094,
            "firstName": "Greg",
            "lastName": "Gregory",
            "phone": "01234567890",
            "email": "greg@email.co.uk",
            "date": "October 1, 2020",
            "time": "14:15",
            "endTime": "15:00",
            "dateCreated": "September 30, 2020",
            "datetimeCreated": "2020-09-30T06:54:07-0500",
            "datetime": "2020-10-01T14:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment - no link",
            "appointmentTypeID": 17271544,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "45",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=2824c95d706bea4ec6604986b9358cd9",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Greg Gregory\nPhone: 01234567890\nEmail: greg@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk"
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "greg@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-10-01",
        "appointment_type": {
            "type_id": "17271544",
            "name": "Development appointment - no link",
            "category": "Tech development",
            "has_link": False,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17271544",
            "type": "acuity-appointment-type"
        }
    },
    'appointment5': {  # hasn't received initial notification yet
        "appointment_id": "451904182",
        "acuity_info": {
            "id": 451904182,
            "firstName": "Eddie",
            "lastName": "Eagleton",
            "phone": "",
            "email": "eddie@email.co.uk",
            "date": "October 15, 2020",
            "time": "11:00",
            "endTime": "11:45",
            "dateCreated": "October 2, 2020",
            "datetimeCreated": "2020-10-01T19:26:20-0500",
            "datetime": "2020-10-15T11:00:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment - no link",
            "appointmentTypeID": 17271544,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "45",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=3b7422961f0ef184e484a94e04e237c9",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": True,
            "canClientReschedule": True,
            "labels": None,
            "forms": [],
            "formsText": "Name: Eddie Eagleton\nPhone: \nEmail: eddie@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk"
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "eddie@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-10-15",
        "appointment_type": {
            "type_id": "17271544",
            "name": "Development appointment - no link",
            "category": "Tech development",
            "has_link": False,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17271544",
            "type": "acuity-appointment-type"
        }
    },
    'appointment6': {  # hasn't received initial notification yet
        "appointment_id": "448161419",
        "acuity_info": {
            "id": 448161419,
            "firstName": "Altha",
            "lastName": "Alcorn",
            "phone": "",
            "email": "altha@email.co.uk",
            "date": "September 28, 2020",
            "time": "10:30",
            "endTime": "11:30",
            "dateCreated": "September 25, 2020",
            "datetimeCreated": "2020-09-25T05:46:24-0500",
            "datetime": "2020-09-28T10:30:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Test appointment - no notifications",
            "appointmentTypeID": 17268193,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "60",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=2013bc86dd386187bc2475eaab50dab3",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Altha Alcorn\nPhone: \nEmail: altha@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk"
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "altha@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-09-28",
        "appointment_type": {
            "type_id": "17268193",
            "name": "Test appointment - no notifications",
            "category": "Tech development",
            "has_link": True,
            "send_notifications": False,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17268193",
            "type": "acuity-appointment-type"
        }
    },
}
